name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile
        run: |
          yarn
          yarn run build

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          action: upload
          # Directory location of the application source code
          app_location: /dist
          azure_static_web_apps_api_token: ${{ secrets.azure_static_web_token }}
          # Custom command for Oryx to run when building Azure Functions source code
          # api_build_command: # optional
          # Directory location of the Azure Functions source code
          # api_location: # optional
          # Directory location of the compiled application code after building
          # app_artifact_location: # optional
          # Custom command for Oryx to run when building application source code
          # app_build_command: yarn run build
          # Token for interacting with the Github repository. Currently used only for commenting on Pull Requests.
          # repo_token: # optional
          # Directory location where the routes.json file can be found in the source code
          # routes_location: # optional
